version: '3.1'
services:
  db:
    # replace username/repo:tag with your name and image details
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: my-database
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3306:3306
    volumes:
      - ~/docker-volumes/data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  apache:
    build: .
    restart: always
    ports:
      - 82:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
